name: rca_resident
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  google_fonts:
  flutter_spinkit:
  shared_preferences: ^2.2.2
  line_icons: ^2.0.1
  calendar_date_picker2:
  dart_jsonwebtoken: ^2.13.0
  get: 4.6.6
  talkjs_flutter:
  carousel_slider: ^5.0.0
  qr_code_scanner_plus: ^2.0.6 
  intl:
  qr_flutter: ^4.1.0
  any_link_preview: ^3.0.2
  cached_network_image: ^3.4.1
  flutter_widget_from_html_core: ^0.15.2
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/rca_logo.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/images/rca_logo.png" # Set the foreground image (same or different from image_path)
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true

dev_dependencies: 
  flutter: 
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

